export default [
  {
    name: "Alice Johnson",
    profilePicture: "https://via.placeholder.com/150",
    bio: "Alice has been teaching English for over 8 years and specializes in Business English.",
    email: "alice.johnson@example.com",
    specialization: "Business English, IELTS Preparation",
    totalCourses: 10,
    totalStudents: 2000,
    rating: 4.7,
    ratingCount: 150,
    socialMedia: {
      linkedin: "https://linkedin.com/in/alicejohnson",
      twitter: "https://twitter.com/alicejohnson",
    },
    experience: 8,
    featuredCourse: {
      title: "Business English for Professionals",
      link: "/courses/business-english",
    },
    achievements: ["TESOL Certified", "Author of 'Mastering Business English'"],
  },
  {
    name: "Bob Smith",
    profilePicture: "https://via.placeholder.com/150",
    bio: "Bob is a Spanish instructor with a passion for helping beginners achieve fluency.",
    email: "bob.smith@example.com",
    specialization: "Spanish for Beginners, Conversational Spanish",
    totalCourses: 8,
    totalStudents: 1800,
    rating: 4.9,
    ratingCount: 200,
    socialMedia: {
      linkedin: "https://linkedin.com/in/bobsmith",
      twitter: "https://twitter.com/bobsmith",
    },
    experience: 6,
    featuredCourse: {
      title: "Conversational Spanish for Beginners",
      link: "/courses/spanish-conversation",
    },
    achievements: ["DELE Certified", "Spanish Language Coach for XYZ Company"],
  },
  {
    name: "Carol Martinez",
    profilePicture: "https://via.placeholder.com/150",
    bio: "Carol is a French instructor with over 10 years of experience teaching all levels.",
    email: "carol.martinez@example.com",
    specialization: "French Language, DELF Preparation",
    totalCourses: 12,
    totalStudents: 2200,
    rating: 4.8,
    ratingCount: 250,
    socialMedia: {
      linkedin: "https://linkedin.com/in/carolmartinez",
      twitter: "https://twitter.com/carolmartinez",
    },
    experience: 10,
    featuredCourse: {
      title: "Mastering French for Intermediate Learners",
      link: "/courses/french-intermediate",
    },
    achievements: ["Certified DELF Examiner", "Best French Teacher Award 2022"],
  },
  {
    name: "David Lee",
    profilePicture: "https://via.placeholder.com/150",
    bio: "David specializes in teaching Japanese and has a unique approach to making learning fun.",
    email: "david.lee@example.com",
    specialization: "Japanese Language, JLPT Preparation",
    totalCourses: 7,
    totalStudents: 1600,
    rating: 4.6,
    ratingCount: 180,
    socialMedia: {
      linkedin: "https://linkedin.com/in/davidlee",
      twitter: "https://twitter.com/davidlee",
    },
    experience: 5,
    featuredCourse: {
      title: "JLPT N5 Preparation Course",
      link: "/courses/jlpt-n5",
    },
    achievements: ["JLPT Certified", "Author of 'Fun with Japanese Grammar'"],
  },
  {
    name: "Eva Chen",
    profilePicture: "https://via.placeholder.com/150",
    bio: "Eva is a Mandarin Chinese instructor with a focus on helping students achieve fluency.",
    email: "eva.chen@example.com",
    specialization: "Mandarin Chinese, HSK Preparation",
    totalCourses: 9,
    totalStudents: 1700,
    rating: 4.9,
    ratingCount: 220,
    socialMedia: {
      linkedin: "https://linkedin.com/in/evachen",
      twitter: "https://twitter.com/evachen",
    },
    experience: 7,
    featuredCourse: {
      title: "Mandarin Chinese for Beginners",
      link: "/courses/mandarin-beginners",
    },
    achievements: ["Certified HSK Examiner", "Top Mandarin Teacher 2023"],
  },
];
