export function LogoutBodyContent() {
  return (
    <div className="p-4">
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
      <h2 className="text-xl font-bold mb-2">Logout Confirmation</h2>
      <p className="mb-4">Are you sure you want to log out?</p>
    </div>
  );
}
